export const OBSERVATIONS_LIST_REQUEST = "OBSERVATIONS_LIST_REQUEST";
export const OBSERVATIONS_LIST_SUCCESS = "OBSERVATIONS_LIST_SUCCESS";
export const OBSERVATIONS_LIST_FAILURE = "OBSERVATIONS_LIST_FAILURE";
